### ISSUE TITLE
Set the maximum value of colorbars of choropleth maps

### ISSUE THREAD

**Issue by mk-repos** [mk-repos/Stats506_group4#1]
In the figures generated by the current function `draw_map_quarter()`, the maximum value of the color bar varies from quarter to quarter.
Since it is desirable to be able to compare color across quarters, how about fixing the maximum value?

In R, we achieve this by first taking the maximum value of positives per quarter `max_positive = max(df_state_q$total_pos)`, and passing that value as x-limit to the function `draw_map_quarter = function(sf_obj, target_q, max_lim)`

**Comment by Lehao25** [comment]
ok, get it.
