### ISSUE TITLE
Comments on the SAS part

### ISSUE THREAD

**Issue by SkyWang0919** [mk-repos/Stats506_group4#10]
Hi Dongyang,
Here are my comments on the SAS part:
1. The style of code exactly follows the guideline.
2. The SAS code is well-structured. Nicely formatted comments make it comfortable for reading.
3. The SAS code is quite efficient without redundancy.
*Nitpick: The q1 to q4 plots in the SAS Document folder seems a little bit small in scale (gathered in the upper-left corner). It can represent the information better if being changed bigger to fit in the plot size.
Sincerely hope that these suggestions can be helpful!

**Comment by mk-repos** [comment]
Thank you, reviewers! This thread is closed because we will raise an issue for each single task that needs to be actually addressed.
