### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by kylewschulz** [mk-repos/Stats506_group4#11]
Hello, 

Here are the results of my peer review... 

**_Core example (R):_**

- R code (in rmd) is very solid. Wish I could find issues with it, but it has consistent styling, is concise, easy enough to follow, and well explained/documented. Very impressive. The core examples are solid and accurate, and the way the group separates each code block for each language is very intuitive.  

**_Common Sections:_**

- Overall the guide is very well organized right now. I particularly enjoy the hyperlinked table of contents that describes what is in the guide quite well. 

- Required sections are included, motivation is described well, data is well described, writing style is clear and concise. 

**_Git:_** 

- Readme is organized very well. I was able to tell who was working on each language easily, along with which issues (none) you had outstanding. 

- Use of the issues feature in git shows evidence of collaboration using git. 

- Evidence of commits from all members. 

- There are a few SAS/python files cluttering up the top-level directory in github. May help navigation to store those under a language folder to make it a bit easier to navigate. I would've expected python files to be in the "python files" folder. 

- Naming/structure could use a bit of work, there's a solid base, but maybe a top level folder for data files, and then a top level folder for code. SAS_document and python_files appear to be all images, which wouldn't be my first guess at what's in there. 

-Otherwise solid git. 

**_Presentation/Style:_** 

- Mentioned in the common section section, but the presentation looks great. Very professional and images are labeled well (good titles/no snakecase). 

Good luck on the rest of your project! 

Kyle

**Comment by Lehao25** [comment]
1. Does the code work? Does it do what it is supposed to? A: The code works smoothly and does all it should do perfectly. 2. How is the style of the code? Does it follow the style guidelines? A: The code are clearly written, functions are implemented to avoid repetition. No obvious style violations are detected. 3. Is the code clearly structured and easy to understand? A: The code are clearly structured and easy to understand with the help of explanations. 4. Is the code efficient? If clarity is sacrificed for efficiency, do the comments help alleviate this? A: The codes are super efficient and the comments are useful in helping explaining the codes. Other considerations: 1. The whole tutorial is kind of long. I do doubt if some parts are really necessary to be explained in detail, like "3.2 How to handle Shapefiles". In short, I think the tutorial is "too detailed". 2. Maybe some part of the codes can be merged together. It may be clearer if there are fewer "python" tabs in each section (like there is only one python tab in "5. Generate Choropleth Maps" and it contains everything from software to Cohropleth graph for four different quarters.) 3. The Choropleth Map are super amazing but it may present better if the graph color is consistent throughout the whole document. Also, the size of some figures may need to be adjusted.
Jialun Li

**Comment by Lehao25** [comment]
Hi Enhao! The main part of the work is done brilliantly, but there's still something you may improve. 1, The official repo looks like a little bit messy, maybe you can try to arrange these files into a more compact and concise way. For example, create SAS, PYTHON, R folder respectively, and put the scripts into the corresponding folder, so people opening the repo can see the work organization immediately. 2, I can not open the html files directly from the github, but I have to download the html file and open it locally. 3, You can label your figure using number, like figure1 figure2, .... 4, In 3,3 the figure is unproportional(too small), and the table in 4.2, geometry is not nicely formatted. 5, Some of the indentation and spacing are not used consistently to maximize readability, I have attached a screenshot as a example. Hope my suggestion can help you! Happy computing, Hongfan.

**Comment by Lehao25** [comment]
> Hello,
> 
> Here are the results of my peer review...
> 
> **_Core example (R):_**
> 
> * R code (in rmd) is very solid. Wish I could find issues with it, but it has consistent styling, is concise, easy enough to follow, and well explained/documented. Very impressive. The core examples are solid and accurate, and the way the group separates each code block for each language is very intuitive.
> 
> **_Common Sections:_**
> 
> * Overall the guide is very well organized right now. I particularly enjoy the hyperlinked table of contents that describes what is in the guide quite well.
> * Required sections are included, motivation is described well, data is well described, writing style is clear and concise.
> 
> **_Git:_**
> 
> * Readme is organized very well. I was able to tell who was working on each language easily, along with which issues (none) you had outstanding.
> * Use of the issues feature in git shows evidence of collaboration using git.
> * Evidence of commits from all members.
> * There are a few SAS/python files cluttering up the top-level directory in github. May help navigation to store those under a language folder to make it a bit easier to navigate. I would've expected python files to be in the "python files" folder.
> * Naming/structure could use a bit of work, there's a solid base, but maybe a top level folder for data files, and then a top level folder for code. SAS_document and python_files appear to be all images, which wouldn't be my first guess at what's in there.
> 
> -Otherwise solid git.
> 
> **_Presentation/Style:_**
> 
> * Mentioned in the common section section, but the presentation looks great. Very professional and images are labeled well (good titles/no snakecase).
> 
> Good luck on the rest of your project!
> 
> Kyle

I have put the code in the corresponding folder and renamed the folder.

**Comment by mk-repos** [comment]
Thank you, reviewers! This thread is closed because we will raise an issue for each single task that needs to be actually addressed.

For members:
Please raise an issue if you think you actually need to address one of the advice from the reviewers.
