### ISSUE TITLE
Remaining tasks in SAS part

### ISSUE THREAD

**Issue by mk-repos** [mk-repos/Stats506_group4#13]
It's already written in your task list, but by the deadline, I think the following changes need to be made.
I believe there isn't much left.

<3.3 How to Draw a US Map>
 - Draw US as a whole (completed)
 - Drop remote islands
 - By using already-shifted shapefile (./maps/shifted), Draw shifted US
   - explain briefly why we use shifted one
	 - Possible explanation: I believe there is no way to implement affine transformation in SAS, like in R/Python

<5.2 Show Choropleth Maps for each Quarter in 2020>
 - Replace the current maps (showing remote islands) with already-shifted shapefile

**Comment by zhaoleo1998** [comment]
Done
