### ISSUE TITLE
Adjust excessive white spaces around figures

### ISSUE THREAD

**Issue by mk-repos** [mk-repos/Stats506_group4#4]
The R and Python output figures sometimes contain large white spaces, which degrade readability (see `main.html`).
We better try to narrow white margins when printing figures.

This may take time, we may keep working on this after the draft deadline.

**Comment by Lehao25** [comment]
The last figure in python is saving as html. When I add title for it in mail.Rmd file, it is hard to narrow the white space. I will try it again. If you have ideas, please tell me.

**Comment by mk-repos** [comment]
My original intention was to remove the extra white space in the png because it was too large.

It turns out that inside `fig.save()`, you can set the options `bbox_inches='tight', pad_inches=0.1`.
I updated `python_extended.ipynb`, and now figures like `transformed_map_python.png` looks much better.

As for html, it may be difficult to adjust as it is a problem with rmarkdown itself.

**Comment by mk-repos** [comment]
I changed the caption for the interactive plot in Python. I just used a regular text in markdown, not a `cap` option in code chunks, because sourced HTML plots do not seem to work with `fig.cap=` option in the first place.
I think it now looks ok.

Also, I adjusted margins in R plots.

I pushed all changes. Please `pull` .Rmd.
