### ISSUE TITLE
Set the maximum value of colorbars of choropleth maps in SAS

### ISSUE THREAD

**Issue by mk-repos** [mk-repos/Stats506_group4#5]
In the figures for each quarter generated by `proc gmap`, the maximum value of the color bar varies from quarter to quarter.
It is misleading that Q1 with small # of cases and Q3 with crazy # of cases have similar color.

Since it is desirable to be able to compare color across quarters, can you fix the color threshold across quarters?

**Comment by zhaoleo1998** [comment]
Gonna added another example that shows how to adjust colors in an extended example.

**Comment by mk-repos** [comment]
The following is a repetition of what we talked about in the chat.

The figures generated in chapter 5.2 should look as identical as possible in R, Python, and SAS.
Therefore, color adjustments are better explained in chapter 5.2, not in the extended examples.

Perhaps there is a way to specify the color of the figure that SAS outputs and a way to fix a range of minimum and maximum values, that vary widely from quarter to quarter in the current code.

**Comment by zhaoleo1998** [comment]
The code has updated to generate the plot you requested. I didn't update the main file yet. Will do it on Tuesday. 
(Updated png files are now located in the SAS/results folder)
