### ISSUE TITLE
Format inline code in markdown

### ISSUE THREAD

**Issue by mk-repos** [mk-repos/Stats506_group4#6]
Currently some of the descriptions in Python sections use single (e.g. ‘draw_map_quarter()’ ) or double quotes (e.g. "sf_obj").
Use grave accent ( ` ) instead of them so that these objects will be shown as an inline code.

‘draw_map_quarter()’  to `draw_map_quarter()`
"sf_obj" to `sf_obj`

**Comment by Lehao25** [comment]
Ok, I have done it.
