### ISSUE TITLE
Compiled shapefile?

### ISSUE THREAD

**Issue by mk-repos** [mk-repos/Stats506_group4#7]
It's only mentioned in README.md, but why does jupyter code use compiled shapefiles?
I think you can complete section 3 without compiling, but can't we use it for extended examples?
If using an externally compiled file is inevitable, please state in the main text why the compilation is necessary and why the compilation cannot be done within the python code.

**Comment by Lehao25** [comment]
Because original maps is too large to plot the last figure for extended example.
I already explain why I have to use compiled map main.Rmd file. But the explanation seems to be in the back part, I will move it to the front
